### ISSUE TITLE
Provisioning

### ISSUE THREAD

**Issue by lstoll** [lstoll/tenderloin#1]
At the moment there is no 'provisioning' setup, we need to add something to bootstrap boxes.

I'm kind of against the Vagrant style magic chef/puppet provisioners - it makes assumptions about how the box is set up, and kicking off these runs isn't hard.

I'm looking at a basic run command or script setup, essentially the 'shell' provisioner. If you want to use chef, you can install it here, and pass in config via shared folders. This is the most flexible and obvious arrangement.

**Comment by lstoll** [comment]
Shipped in v0.3.0

**Comment by benburkert** [comment]
> I'm kind of against the Vagrant style magic chef/puppet provisioners - it makes assumptions about how the box is set up, and kicking off these runs isn't hard.

+10,000. keep it simple. there's really no need to mount NFS or any of that nonsense either. shell scripts & rsync work well enough, and can be used to bootstrap any of that more tricky crap.

**Comment by lstoll** [comment]
This has shipped in 0.3.0

You can
- share folders
- run a command
- or run a script

And that's it. You should be able to trivially figure anything out from here, if you don't you need to learn your tools better.
