### ISSUE TITLE
Restructure proposal

### ISSUE THREAD

**Issue by lstoll** [lstoll/tenderloin#15]
Currently the code is a bit of a mess - it's hacks on top of hacks on an old Vagrant, so it's not the most beautiful thing

Then there's [fog-tenderloin](/lstoll/fog-tenderloin), which is even more hacks on top of this, with shelling out and all kinds of fun.

The result is an _interface_ that I like, but with an implementation I don't. So it's time to think this.

What I'm thinking about doing is pushing the underlying fusion and box management implementation in to fog-tenderloin. The Servers model would interact directly with defined VMs in ~/.tenderloin and fusion, and the Templates model would interact with boxes.

The tenderloin gem would provide the CLI & configuration DSL as a wrapper around this.

The fog implementation would be api-compatible with fog-oc, which means we can treat the two as equivalent in both, and use the Tenderfile/CLI with both backends.

@calavera @benburkert

**Comment by calavera** [comment]
damn, I was about to start working on this!
